// ─────────────────────────────────────────────────────────────
//  TOOL REGISTRY — single source of truth.
//  Add a tool here + create its page and it automatically gets:
//  metadata, canonical, Open Graph, JSON-LD (App, HowTo, FAQ,
//  Breadcrumb), sitemap entry, nav/footer links, related links, ads.
// ─────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: 'pdf', name: 'PDF Tools', path: '/pdf-tools', icon: '📄', color: '#C2410C',
    title: 'Free PDF Tools Online', blurb: 'Split, merge, compress and create PDFs privately in your browser.',
    description: 'Free online PDF tools: split PDF pages, merge PDF files, compress PDF size and convert images to PDF. No upload, no sign-up.' },
  { id: 'image', name: 'Image Tools', path: '/category/image', icon: '🖼️', color: '#7C3AED',
    title: 'Free Image Tools Online', blurb: 'Convert, compress and resize photos without uploading them.',
    description: 'Free online image tools: convert JPG, PNG and WebP, compress image size and resize photos. Fast, private, no sign-up.' },
  { id: 'text', name: 'Text Tools', path: '/category/text', icon: '✍️', color: '#2563EB',
    title: 'Free Text Tools Online', blurb: 'Count words and fix text case in one click.',
    description: 'Free online text tools: word and character counter, case converter and more. Instant results in your browser.' },
  { id: 'calc', name: 'Calculators', path: '/category/calculators', icon: '🧮', color: '#B45309',
    title: 'Free Online Calculators', blurb: 'BMI, age, percentage and loan EMI calculators.',
    description: 'Free online calculators: BMI calculator, age calculator, percentage calculator and loan EMI calculator.' },
  { id: 'convert', name: 'Converters', path: '/category/converters', icon: '🔄', color: '#0B7A5E',
    title: 'Free Online Converters', blurb: 'Currency, height, units and colors.',
    description: 'Free online converters: live currency converter, feet to cm height converter, unit converter and HEX/RGB/HSL color converter.' },
  { id: 'dev', name: 'Developer & Web Tools', path: '/category/developer', icon: '🧰', color: '#0E7490',
    title: 'Free Developer & Web Tools', blurb: 'JSON, Base64, passwords and QR codes.',
    description: 'Free developer and web tools: JSON formatter and validator, Base64 encoder/decoder, password generator and QR code generator.' },
];

const T = (t) => ({ keywords: [], related: [], ...t });

export const TOOLS = [
  // ───────────── PDF ─────────────
  T({ id: 'pdf-splitter', path: '/pdf-tools/splitter', cat: 'pdf', icon: '✂️', name: 'PDF Splitter',
    short: 'Extract pages or ranges from any PDF.',
    title: 'Free PDF Splitter – Extract Pages Online',
    description: 'Split a PDF or extract specific pages like 1-3, 5, 10-12 in seconds. Free, private PDF splitter that runs in your browser — no upload.',
    keywords: ['split pdf', 'pdf splitter', 'extract pdf pages', 'separate pdf pages', 'cut pdf online'],
    intro: 'Pull out the pages you need from a PDF. Type a page range, click once and download a new PDF. Your file never leaves your device.',
    steps: ['Drop your PDF into the upload box.', 'Enter the pages to keep, for example 1-3, 5, 10-12.', 'Press Split & download and save the new PDF.'],
    features: ['Works fully offline in your browser', 'Supports ranges and single pages together', 'No watermark, no page limit, no account'],
    faqs: [
      ['How do I extract pages from a PDF?', 'Upload the PDF, type the page numbers or ranges you want (such as 2-4, 9) and click Split & download. A new PDF containing only those pages is created.'],
      ['Is my PDF uploaded to a server?', 'No. The file is processed locally using your browser, so confidential documents stay on your device.'],
      ['Is there a page or size limit?', 'There is no fixed limit. Very large files depend on your device memory, so close other heavy tabs if a big PDF is slow.'],
    ],
    related: ['pdf-merger', 'pdf-compressor', 'image-to-pdf'] }),
  T({ id: 'pdf-merger', path: '/pdf-tools/merger', cat: 'pdf', icon: '🧷', name: 'PDF Merger',
    short: 'Combine several PDFs into one file.',
    title: 'Merge PDF Files Online – Free PDF Merger',
    description: 'Combine multiple PDF files into a single document. Reorder files, merge instantly and download — free, no upload, no watermark.',
    keywords: ['merge pdf', 'combine pdf', 'pdf merger', 'join pdf files', 'pdf combiner'],
    intro: 'Join two or more PDFs into one tidy document. Arrange the order, merge and download — all inside your browser.',
    steps: ['Add two or more PDF files.', 'Use the arrows to put them in the right order.', 'Click Merge & download to get one combined PDF.'],
    features: ['Reorder files before merging', 'Private — nothing is uploaded', 'Unlimited merges, no watermark'],
    faqs: [
      ['How do I combine PDF files into one?', 'Select all the PDFs, order them with the arrow buttons and press Merge & download. The pages are joined in the order shown.'],
      ['Can I merge more than two PDFs?', 'Yes. Add as many files as you like; they are merged top to bottom.'],
      ['Will merging reduce quality?', 'No. Pages are copied as they are, so text and images keep their original quality.'],
    ],
    related: ['pdf-splitter', 'pdf-compressor', 'image-to-pdf'] }),
  T({ id: 'pdf-compressor', path: '/pdf-tools/compressor', cat: 'pdf', icon: '📉', name: 'PDF Compressor',
    short: 'Optimise a PDF to make the file smaller.',
    title: 'Compress PDF Online – Reduce PDF Size',
    description: 'Optimise and shrink PDF file size in your browser. Free PDF compressor with before/after size, no upload and no sign-up.',
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor', 'shrink pdf', 'make pdf smaller'],
    intro: 'Optimise the internal structure of your PDF and see exactly how many KB you saved. Files are processed privately on your device.',
    steps: ['Upload the PDF you want to optimise.', 'Choose a compression level.', 'Click Compress and download the smaller file.'],
    features: ['Shows original vs. new size', 'Runs locally — your document stays private', 'Free, no watermark'],
    faqs: [
      ['How much can a PDF be reduced?', 'Results depend on the file. PDFs with redundant structure shrink the most; PDFs made mostly of already-compressed photos may change little.'],
      ['Is compressing a PDF safe for private files?', 'Yes. Compression happens in your browser and the file is never sent to our servers.'],
      ['Why did my PDF barely get smaller?', 'If the PDF is mostly large photos, it is already compressed. Try compressing the original images first with our Image Compressor, then rebuild with JPG to PDF.'],
    ],
    related: ['pdf-splitter', 'pdf-merger', 'image-compressor'] }),
  T({ id: 'image-to-pdf', path: '/pdf-tools/image-to-pdf', cat: 'pdf', icon: '🗂️', name: 'JPG to PDF',
    short: 'Turn JPG and PNG images into one PDF.',
    title: 'JPG to PDF Converter – Images to PDF',
    description: 'Convert JPG and PNG images to a single PDF. Reorder pages, pick A4 or original size. Free, private image to PDF converter.',
    keywords: ['jpg to pdf', 'image to pdf', 'png to pdf', 'photo to pdf', 'convert images to pdf'],
    intro: 'Combine photos or scans into one PDF. Choose page size, reorder images and download — processed entirely in your browser.',
    steps: ['Add one or more JPG or PNG images.', 'Reorder them and choose A4 or fit-to-image page size.', 'Click Create PDF and download.'],
    features: ['Multiple images into one PDF', 'A4 or original image size', 'No upload, no watermark'],
    faqs: [
      ['How do I convert a JPG to PDF?', 'Add your JPG, choose the page size and click Create PDF. You can add several images to make a multi-page document.'],
      ['Which image formats are supported?', 'JPG, JPEG and PNG. For WebP or other formats, convert them first with our Image Converter.'],
      ['Are my photos uploaded anywhere?', 'No. The PDF is generated locally in your browser.'],
    ],
    related: ['image-converter', 'pdf-merger', 'image-compressor'] }),

  // ───────────── IMAGE ─────────────
  T({ id: 'image-converter', path: '/image-converter', cat: 'image', icon: '🔁', name: 'Image Converter',
    short: 'Convert between JPG, PNG and WebP.',
    title: 'Image Converter – JPG, PNG & WebP Online',
    description: 'Convert images between JPG, PNG and WebP instantly. Free online image converter with transparent-background handling, no upload.',
    keywords: ['image converter', 'jpg to png', 'png to jpg', 'webp to jpg', 'jpg to webp', 'convert image format'],
    intro: 'Switch any picture between JPG, PNG and WebP in one click. Conversion happens in your browser, so photos stay private.',
    steps: ['Upload a JPG, PNG or WebP image.', 'Pick the format you want.', 'Click Convert and download the result.'],
    features: ['PNG, JPG and WebP output', 'Transparent areas become white when saving as JPG', 'Private — files never leave your device'],
    faqs: [
      ['How do I convert PNG to JPG?', 'Upload the PNG, choose JPG as the output and click Convert. Transparent areas are filled with white because JPG has no transparency.'],
      ['Is WebP better than JPG?', 'WebP usually gives smaller files at similar quality, which makes pages load faster. JPG is more universally supported in older software.'],
      ['Does converting reduce quality?', 'PNG output is lossless. JPG and WebP are lossy; this tool uses high quality settings to keep differences invisible.'],
    ],
    related: ['image-compressor', 'image-resizer', 'image-to-pdf'] }),
  T({ id: 'image-compressor', path: '/image-compressor', cat: 'image', icon: '🗜️', name: 'Image Compressor',
    short: 'Shrink JPG, PNG and WebP file sizes.',
    title: 'Image Compressor – Reduce JPG, PNG Size',
    description: 'Compress JPG, PNG and WebP images online with a quality slider and live size preview. Free, private, no upload.',
    keywords: ['image compressor', 'compress jpg', 'reduce image size', 'compress photo', 'shrink image online'],
    intro: 'Make photos lighter for email, forms and websites. Slide the quality, compare sizes and download the smaller image.',
    steps: ['Upload an image.', 'Drag the quality slider and watch the size change.', 'Download the compressed image.'],
    features: ['Live before/after size', 'Output as JPG or WebP', 'Nothing is uploaded'],
    faqs: [
      ['What quality setting should I use?', 'Around 70–80% is a good balance: files shrink a lot while still looking sharp on screen.'],
      ['Which format compresses best?', 'WebP is usually smallest. Choose JPG when you need the widest compatibility.'],
      ['Can I compress for a form upload limit?', 'Yes — lower the quality or resize the image first until the displayed size is under the limit (for example 200 KB).'],
    ],
    related: ['image-resizer', 'image-converter', 'pdf-compressor'] }),
  T({ id: 'image-resizer', path: '/image-resizer', cat: 'image', icon: '📐', name: 'Image Resizer',
    short: 'Resize photos by pixels or percentage.',
    title: 'Image Resizer – Resize Photos Online',
    description: 'Resize images to exact width and height or by percentage. Keeps aspect ratio, free, private and runs in your browser.',
    keywords: ['image resizer', 'resize image', 'resize photo online', 'change image dimensions', 'photo resizer'],
    intro: 'Set a new width and height in pixels, or scale by percentage. Lock the aspect ratio to avoid stretching.',
    steps: ['Upload your image.', 'Enter new width or height (aspect ratio stays locked).', 'Click Resize and download.'],
    features: ['Aspect-ratio lock', 'Exact pixel control', 'Private browser processing'],
    faqs: [
      ['How do I resize an image without losing quality?', 'Scaling down keeps images sharp. Enlarging beyond the original size can look soft because no new detail exists.'],
      ['What size is best for social media?', 'Common sizes: 1080×1080 for square posts, 1200×630 for link previews and 1920×1080 for video thumbnails.'],
      ['Does it keep the file format?', 'Yes. PNG stays PNG and JPG stays JPG unless you change it in the Image Converter.'],
    ],
    related: ['image-compressor', 'image-converter', 'image-to-pdf'] }),

  // ───────────── TEXT ─────────────
  T({ id: 'word-counter', path: '/word-counter', cat: 'text', icon: '🔤', name: 'Word Counter',
    short: 'Count words, characters, sentences and reading time.',
    title: 'Word Counter – Count Words & Characters',
    description: 'Count words, characters, sentences and paragraphs with reading time and top keywords. Free online word counter for essays and SEO.',
    keywords: ['word counter', 'character counter', 'count words', 'letter count', 'reading time calculator'],
    intro: 'Paste or type your text and see live counts for words, characters, sentences, paragraphs and estimated reading time.',
    steps: ['Paste or type text in the box.', 'Read the live statistics above it.', 'Check top keywords to avoid repeating words.'],
    features: ['Live counts as you type', 'Reading and speaking time', 'Keyword frequency list'],
    faqs: [
      ['How are words counted?', 'Words are groups of characters separated by spaces or line breaks. Hyphenated words count as one.'],
      ['How is reading time estimated?', 'We assume about 225 words per minute for silent reading and 130 for speaking aloud.'],
      ['Are my texts saved?', 'No. Everything stays in your browser and disappears when you close the tab.'],
    ],
    related: ['case-converter', 'percentage-calculator', 'json-formatter'] }),
  T({ id: 'case-converter', path: '/case-converter', cat: 'text', icon: '🔠', name: 'Case Converter',
    short: 'UPPERCASE, lowercase, Title Case and more.',
    title: 'Case Converter – UPPER, lower, Title Case',
    description: 'Convert text to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case and kebab-case in one click.',
    keywords: ['case converter', 'uppercase to lowercase', 'title case converter', 'sentence case', 'camelCase converter'],
    intro: 'Fix text that was typed with caps lock on, format headlines, or turn phrases into code-friendly names.',
    steps: ['Paste your text.', 'Click the case style you want.', 'Copy the result.'],
    features: ['9 case styles', 'One-click copy', 'Works on long documents'],
    faqs: [
      ['What is title case?', 'Title Case capitalises the first letter of each main word, commonly used for headlines.'],
      ['What is the difference between camelCase and snake_case?', 'camelCase joins words with capital letters (myVariable); snake_case joins them with underscores (my_variable).'],
      ['Can I undo a conversion?', 'Use the original text box: your input is kept, so you can click a different style any time.'],
    ],
    related: ['word-counter', 'base64', 'json-formatter'] }),

  // ───────────── CALCULATORS ─────────────
  T({ id: 'bmi-calculator', path: '/bmi-calculator', cat: 'calc', icon: '⚖️', name: 'BMI Calculator',
    short: 'Body mass index in metric or imperial.',
    title: 'BMI Calculator – Check Your Body Mass Index',
    description: 'Calculate your BMI in kg/cm or lb/ft-in and see your WHO category and healthy weight range. Free, instant, private.',
    keywords: ['bmi calculator', 'body mass index', 'healthy weight', 'bmi chart', 'calculate bmi'],
    intro: 'Enter your height and weight to get your body mass index and the matching WHO category, plus the weight range considered healthy for your height.',
    steps: ['Choose metric or imperial units.', 'Enter height and weight.', 'Read your BMI, category and healthy range.'],
    features: ['Metric and imperial', 'WHO categories', 'Healthy weight range for your height'],
    faqs: [
      ['How is BMI calculated?', 'BMI = weight in kilograms ÷ height in metres squared. For pounds and inches the formula is 703 × lb ÷ in².'],
      ['What is a healthy BMI?', 'The WHO lists 18.5 to 24.9 as the normal range for most adults.'],
      ['Is BMI always accurate?', 'No. BMI does not separate muscle from fat, so athletes may score high. It is a screening number, not a diagnosis — speak with a health professional for advice.'],
    ],
    related: ['age-calculator', 'percentage-calculator', 'unit-converter'] }),
  T({ id: 'age-calculator', path: '/age-calculator', cat: 'calc', icon: '🎂', name: 'Age Calculator',
    short: 'Exact age in years, months and days.',
    title: 'Age Calculator – Exact Age in Years & Days',
    description: 'Find your exact age in years, months, days and total days lived, plus days until your next birthday. Free age calculator.',
    keywords: ['age calculator', 'calculate age', 'date of birth calculator', 'how old am i', 'days until birthday'],
    intro: 'Enter a birth date to see exact age, total days lived and a countdown to the next birthday.',
    steps: ['Pick your date of birth.', 'Optionally change the “age at” date.', 'Read your age breakdown.'],
    features: ['Years, months and days', 'Total days and weeks lived', 'Next birthday countdown'],
    faqs: [
      ['How is age calculated?', 'We count full years since the birth date, then the remaining full months and days up to the chosen date.'],
      ['Can I calculate age on a past or future date?', 'Yes. Change the “Age at” date to any day to see the age on that date.'],
      ['Does it handle leap years?', 'Yes. Calendar maths is handled by your browser, including February 29.'],
    ],
    related: ['bmi-calculator', 'percentage-calculator', 'unit-converter'] }),
  T({ id: 'percentage-calculator', path: '/percentage-calculator', cat: 'calc', icon: '％', name: 'Percentage Calculator',
    short: 'Percent of, percent change and what percent.',
    title: 'Percentage Calculator – Quick % Math',
    description: 'Calculate X% of a number, what percent one number is of another, and percentage increase or decrease. Free online calculator.',
    keywords: ['percentage calculator', 'percent calculator', 'percentage change', 'what percent of', 'discount calculator'],
    intro: 'Three everyday percentage calculations in one place — perfect for discounts, tips, grades and growth rates.',
    steps: ['Pick the question that matches yours.', 'Enter the two numbers.', 'The answer updates instantly.'],
    features: ['Percent of a number', 'Percentage increase / decrease', 'Instant results'],
    faqs: [
      ['How do I calculate a percentage of a number?', 'Multiply the number by the percentage and divide by 100. Example: 15% of 200 = 200 × 15 ÷ 100 = 30.'],
      ['How do I calculate percentage change?', '(New − Old) ÷ Old × 100. A positive result is an increase, negative is a decrease.'],
      ['How do I calculate a discount?', 'Use “% of”: the discount amount is price × discount % ÷ 100. Subtract it from the price for the sale price.'],
    ],
    related: ['emi-calculator', 'bmi-calculator', 'word-counter'] }),
  T({ id: 'emi-calculator', path: '/emi-calculator', cat: 'calc', icon: '🏦', name: 'EMI / Loan Calculator',
    short: 'Monthly payment, total interest and schedule.',
    title: 'EMI Calculator – Loan Payment Calculator',
    description: 'Calculate monthly loan EMI, total interest and total payment for home, car or personal loans, with a yearly breakdown.',
    keywords: ['emi calculator', 'loan calculator', 'monthly payment calculator', 'home loan emi', 'car loan calculator'],
    intro: 'Enter the loan amount, annual interest rate and term to see your monthly instalment, total interest and a year-by-year balance.',
    steps: ['Enter loan amount, interest rate and term.', 'Choose years or months.', 'Review EMI, total interest and the yearly table.'],
    features: ['Works for any currency', 'Principal vs. interest split', 'Yearly balance table'],
    faqs: [
      ['What is EMI?', 'EMI (equated monthly instalment) is the fixed amount you pay each month, covering both interest and part of the principal.'],
      ['What is the EMI formula?', 'EMI = P × r × (1+r)^n ÷ ((1+r)^n − 1), where P is the loan, r the monthly rate and n the number of months.'],
      ['Does this include fees or insurance?', 'No. Results cover interest and principal only, so check your lender’s fees separately. This is an estimate, not financial advice.'],
    ],
    related: ['percentage-calculator', 'exchange-rate', 'age-calculator'] }),

  // ───────────── CONVERTERS ─────────────
  T({ id: 'exchange-rate', path: '/exchange-rate', cat: 'convert', icon: '💱', name: 'Currency Converter',
    short: 'Live rates for 160+ world currencies.',
    title: 'Currency Converter – Live Exchange Rates',
    description: 'Convert 160+ currencies with live exchange rates. USD to THB, MMK, EUR, JPY and more. Free, fast and updated daily.',
    keywords: ['currency converter', 'exchange rate', 'usd to thb', 'usd to mmk', 'live exchange rates', 'forex calculator'],
    intro: 'Check today’s exchange rate and convert any amount between more than 160 world currencies.',
    steps: ['Enter the amount.', 'Choose the From and To currencies (use ⇄ to swap).', 'See the converted amount and the rate instantly.'],
    features: ['160+ currencies', 'Daily-updated mid-market rates', 'One-click swap'],
    faqs: [
      ['How often are exchange rates updated?', 'Rates are refreshed about once per day from a public exchange-rate feed and cached for an hour.'],
      ['Why is my bank rate different?', 'Banks and money-transfer services add a margin to the mid-market rate shown here, so the real amount you receive is usually lower.'],
      ['Can I use this for travel budgeting?', 'Yes, for planning. Check your card or exchange counter for the exact rate and fees before you transact.'],
    ],
    related: ['unit-converter', 'emi-calculator', 'percentage-calculator'] }),
  T({ id: 'height-converter', path: '/height-converter', cat: 'convert', icon: '📏', name: 'Height Converter',
    short: 'Feet & inches to cm, and back.',
    title: 'Height Converter – Feet & Inches to CM',
    description: 'Convert height between feet/inches and centimeters in both directions. Handy for passports, medical forms and fitness tracking.',
    keywords: ['height converter', 'feet to cm', 'inches to cm', 'cm to feet', 'cm to ft and inches', 'height in cm'],
    intro: 'Convert 5 ft 9 in to centimeters — or centimeters back to feet and inches — instantly.',
    steps: ['Choose the direction.', 'Enter your height.', 'Read the result, ready for forms and records.'],
    features: ['Two-way conversion', 'Exact formula (1 in = 2.54 cm)', 'Common heights table'],
    faqs: [
      ['How many cm is 5 feet 6 inches?', '5 ft 6 in = 66 inches × 2.54 = 167.64 cm.'],
      ['How do I convert cm to feet and inches?', 'Divide centimeters by 2.54 to get total inches, then divide by 12 for feet; the remainder is inches.'],
      ['How many centimeters are in a foot?', 'One foot equals 30.48 centimeters.'],
    ],
    related: ['unit-converter', 'bmi-calculator', 'image-resizer'] }),
  T({ id: 'unit-converter', path: '/unit-converter', cat: 'convert', icon: '🔀', name: 'Unit Converter',
    short: 'Length, weight, temperature, volume, speed.',
    title: 'Unit Converter – Length, Weight, Temperature',
    description: 'Convert length, weight, temperature, volume and speed units instantly: km to miles, kg to lb, °C to °F, liters to gallons and more.',
    keywords: ['unit converter', 'km to miles', 'kg to lbs', 'celsius to fahrenheit', 'metric converter', 'measurement converter'],
    intro: 'Pick a category, choose two units and type a value. The converted value updates as you type.',
    steps: ['Select a category such as Length or Weight.', 'Choose From and To units.', 'Enter a value and read the result.'],
    features: ['5 categories, 30+ units', 'Instant two-way results', 'Swap button'],
    faqs: [
      ['How do I convert Celsius to Fahrenheit?', 'Multiply by 9/5 and add 32. Example: 25 °C = 77 °F.'],
      ['How many kilometers are in a mile?', 'One mile equals 1.609344 kilometers.'],
      ['How many pounds are in a kilogram?', 'One kilogram equals about 2.20462 pounds.'],
    ],
    related: ['height-converter', 'exchange-rate', 'bmi-calculator'] }),
  T({ id: 'color-converter', path: '/color-converter', cat: 'convert', icon: '🎨', name: 'Color Converter',
    short: 'HEX, RGB and HSL with a live picker.',
    title: 'Color Converter – HEX, RGB & HSL',
    description: 'Convert colors between HEX, RGB and HSL with a live color picker and one-click copy. Free tool for designers and developers.',
    keywords: ['color converter', 'hex to rgb', 'rgb to hex', 'hsl converter', 'color picker'],
    intro: 'Pick a color or paste a HEX code and get matching RGB and HSL values for CSS and design tools.',
    steps: ['Pick a color or type a HEX code.', 'Read the RGB and HSL values.', 'Click copy for the format you need.'],
    features: ['HEX, RGB, HSL', 'Visual color picker', 'CSS-ready, one-click copy'],
    faqs: [
      ['How do I convert HEX to RGB?', 'Split the six hex digits into three pairs and convert each from base 16 to decimal. #0B7A5E becomes rgb(11, 122, 94).'],
      ['What is HSL?', 'HSL stands for hue, saturation and lightness. It makes it easy to create lighter or darker shades of the same color.'],
      ['Which format should I use in CSS?', 'All three work. HEX is compact, RGB is common with transparency (rgba), and HSL is easiest to adjust by hand.'],
    ],
    related: ['unit-converter', 'base64', 'json-formatter'] }),

  // ───────────── DEV / WEB ─────────────
  T({ id: 'json-formatter', path: '/json-formatter', cat: 'dev', icon: '🧾', name: 'JSON Formatter',
    short: 'Beautify, minify and validate JSON.',
    title: 'JSON Formatter & Validator – Beautify JSON',
    description: 'Format, beautify, minify and validate JSON online. Shows the exact error position. Free, private, runs in your browser.',
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json minify', 'pretty print json'],
    intro: 'Paste messy JSON to format it with indentation, minify it for production, or find out why it is invalid.',
    steps: ['Paste your JSON.', 'Click Format, Minify or Validate.', 'Copy the clean output.'],
    features: ['Clear error messages', '2-space, 4-space or tab indent', 'Data never leaves your browser'],
    faqs: [
      ['How do I validate JSON?', 'Paste it and click Format. If the JSON is invalid you will see the error message and where parsing failed.'],
      ['What are common JSON errors?', 'Trailing commas, single quotes instead of double quotes, and unquoted keys are the most frequent mistakes.'],
      ['Is it safe to paste API responses?', 'Yes. Parsing happens locally; nothing is sent to a server.'],
    ],
    related: ['base64', 'word-counter', 'password-generator'] }),
  T({ id: 'base64', path: '/base64', cat: 'dev', icon: '🔐', name: 'Base64 Encode / Decode',
    short: 'Encode or decode text with full Unicode support.',
    title: 'Base64 Encode & Decode Online',
    description: 'Encode text to Base64 or decode Base64 back to text with full UTF-8 and emoji support. Free, instant, and private — nothing is uploaded.',
    keywords: ['base64 encode', 'base64 decode', 'base64 converter', 'text to base64', 'decode base64 string'],
    intro: 'Convert plain text to Base64 and back. Handles accents, Thai, Burmese, emoji and any other Unicode text.',
    steps: ['Choose Encode or Decode.', 'Paste your text.', 'Copy the result.'],
    features: ['Full UTF-8 support', 'Clear error on invalid input', 'Instant, local processing'],
    faqs: [
      ['What is Base64?', 'Base64 is a way to represent binary or text data using only letters, digits, + and /, so it can travel safely through systems that expect plain text.'],
      ['Is Base64 encryption?', 'No. It is an encoding, not encryption — anyone can decode it. Never use it to hide passwords.'],
      ['Why does decoding fail?', 'The input probably has missing characters, extra spaces or is not Base64. Check for a truncated copy.'],
    ],
    related: ['json-formatter', 'password-generator', 'case-converter'] }),
  T({ id: 'password-generator', path: '/password-generator', cat: 'dev', icon: '🔑', name: 'Password Generator',
    short: 'Strong random passwords, made on your device.',
    title: 'Password Generator – Strong Random Passwords',
    description: 'Generate strong, random passwords with custom length and symbols. Uses your browser’s secure random generator — never stored or sent.',
    keywords: ['password generator', 'strong password generator', 'random password', 'secure password', 'passphrase'],
    intro: 'Create a unique password for every account. Passwords are generated with your device’s cryptographic random source and never leave the page.',
    steps: ['Set the length and character types.', 'Click Generate.', 'Copy the password into your password manager.'],
    features: ['Cryptographically secure randomness', 'Strength meter', 'Nothing stored or transmitted'],
    faqs: [
      ['How long should a password be?', 'At least 14 characters. Longer is better, and 16+ with mixed characters is considered very strong.'],
      ['Is this generator safe?', 'Yes. It uses crypto.getRandomValues in your browser. The password is never sent to or stored on a server.'],
      ['Should I memorise these passwords?', 'No — store them in a reputable password manager and use a unique password for each site.'],
    ],
    related: ['qr-code-generator', 'base64', 'json-formatter'] }),
  T({ id: 'qr-code-generator', path: '/qr-code-generator', cat: 'dev', icon: '🔳', name: 'QR Code Generator',
    short: 'QR codes for links, text and Wi-Fi.',
    title: 'QR Code Generator – Free QR Codes',
    description: 'Create QR codes for URLs, text or Wi-Fi and download them as PNG. Custom size and colors, static codes that never expire. Free.',
    keywords: ['qr code generator', 'create qr code', 'url to qr code', 'wifi qr code', 'free qr code'],
    intro: 'Turn a link, message or Wi-Fi login into a scannable QR code. Choose colors and size, then download a PNG.',
    steps: ['Choose URL/Text or Wi-Fi.', 'Enter your content and pick size and colors.', 'Download the PNG.'],
    features: ['URL, text and Wi-Fi codes', 'Custom colors and size', 'Never expires — static codes'],
    faqs: [
      ['Do these QR codes expire?', 'No. They are static codes that encode your data directly, so they work forever with no tracking or redirect.'],
      ['What size should I print?', 'At least 2 × 2 cm (0.8 in). Keep strong contrast between code and background.'],
      ['Can I make a Wi-Fi QR code?', 'Yes. Choose Wi-Fi, enter the network name and password; phones can join by scanning.'],
    ],
    related: ['password-generator', 'base64', 'image-converter'] }),
];

export const TOOL_BY_ID = Object.fromEntries(TOOLS.map((t) => [t.id, t]));
export const TOOL_BY_PATH = Object.fromEntries(TOOLS.map((t) => [t.path, t]));
export const CAT_BY_ID = Object.fromEntries(CATEGORIES.map((c) => [c.id, c]));
export const toolsIn = (catId) => TOOLS.filter((t) => t.cat === catId);
export const relatedOf = (tool) => tool.related.map((id) => TOOL_BY_ID[id]).filter(Boolean);
